### ISSUE TITLE
AsyncClient does not have MQTTAsync_destroy called on drop

### ISSUE THREAD

**Issue by jnicholls** [eclipse/paho.mqtt.rust#10]
It appears the `AsyncClient` leaks memory when it is dropped, as the underlying `MQTTAsync_destroy` function is not called for the `handle` inside the `AsyncClient`. In addition to cleaning up its internal memory allocations, it would also ensure the client properly is disconnected and shut down and not just left hanging open.

**Comment by fpagliughi** [comment]
This was fixed by #11, if I'm not mistaken.
