### ISSUE TITLE
error: build failed

### ISSUE THREAD

**Issue by Alvazz** [eclipse/paho.mqtt.rust#104]
Env:

cpu: Quad-core 64-bit Cortex-A53  aarch64

`error: failed to run custom build command for `paho-mqtt-sys v0.4.0 (https://github.com/eclipse/paho.mqtt.rust.git?branch=master#976e7ea5)`

Caused by:
  process didn't exit successfully: `/home/admin/mqttest/mqtt-xcx/target/debug/build/paho-mqtt-sys-19f12692e62305a7/build-script-build` (exit code: 101)
  --- stdout
  debug:Running the bundled build for Paho C
  cargo:rerun-if-changed=build.rs
  running: "cmake" "/root/.cargo/git/checkouts/paho.mqtt.rust-44b07fd42c95bba6/976e7ea/paho-mqtt-sys/paho.mqtt.c/" "-DPAHO_BUILD_SHARED=off" "-DPAHO_BUILD_STATIC=on" "-DPAHO_ENABLE_TESTING=off" "-DPAHO_HIGH_PERFORMANCE=on" "-DPAHO_WITH_SSL=on" "-DCMAKE_INSTALL_PREFIX=/home/admin/mqttest/mqtt-xcx/target/debug/build/paho-mqtt-sys-8fabf935bf9590d8/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- The C compiler identification is GNU 6.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- CMake version: 3.7.2
  -- CMake system name: Linux
  -- The CXX compiler identification is GNU 6.3.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Timestamp is 2020-11-16T05:07:32Z
  -- Configuring incomplete, errors occurred!
  See also "/home/admin/mqttest/mqtt-xcx/target/debug/build/paho-mqtt-sys-8fabf935bf9590d8/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
    Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
    system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
    OPENSSL_INCLUDE_DIR)
  Call Stack (most recent call first):
    /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.7/Modules/FindOpenSSL.cmake:385 (find_package_handle_standard_args)
    src/CMakeLists.txt:186 (find_package)

  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cmake-0.1.44/src/lib.rs:885:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by Alvazz** [comment]
ok, i found it. just need apt-get install libssl-dev.

**Comment by homeassistant-hacs-m** [comment]
This doesn't solve `paho-mqtt = { version = "0.12.1", features = ["vendored-ssl"] }` under `cross check --target mips-unknown-linux-musl` :/
