### ISSUE TITLE
Set log level to LOG_ERROR

### ISSUE THREAD

**Issue by tobdub** [eclipse/paho.mqtt.rust#111]
The log level can now be set to `LOG_ERROR` in the C lib, https://github.com/eclipse/paho.mqtt.c/commit/9942cb107a23cf37be41e44da91970dfbd8aaf2e.
This improves performance by around 10% for my use case.

**Comment by tobdub** [comment]
Actually it looks like `TRACE_PROTOCOL` is the new minimum level, so using LOG_ERROR doesn't help :(

**Comment by fpagliughi** [comment]
Is there anything that can/should be done in the Rust library to help with this?

**Comment by tobdub** [comment]
Yes, need to add a call to `Log_setTraceLevel(LOG_ERROR)` somewhere since the default is `TRACE_MINIMUM`.
However, it seems it currently doesn't have any effect if the C lib is not updated.

**Comment by fpagliughi** [comment]
I don't think any of the Log functions are publicly exported out of the C library. I made that mistake with the v0.7 Rust lib. That was a bad one.

**Comment by tobdub** [comment]
Aah, OK. Maybe the default trace/log level can be changed in the C lib if the `HIGH_PERFORMANCE` flag is set.

**Comment by fpagliughi** [comment]
As an aside, I'm moving forward with the v0.9 release - hopefully by the end of the day, today - using the C v1.3.8 release.

After this, though, I believe that I'll have most of the features that I need for the near future, and would like to start  looking more into performance. A lot of that will depend on what changes we can get into the C library.
