### ISSUE TITLE
Getting "Paho(-2)" error when connecting to mosquitto from within a Docker container not as root

### ISSUE THREAD

**Issue by dwaynebradley** [eclipse/paho.mqtt.rust#115]
In my Cargo.toml file, I'm referencing the `paho-mqtt` crate like this:

```
openssl = { version = "0.10.32", features = ["vendored"] }
paho-mqtt = { version = "0.9.1", features = ["vendored-ssl"] }
```

I have the `openssl` crate there as there are other dependencies that depend on `openssl` and I want them to statically link as well. I am successfully compiling my application using:

```
cross build --release --target=x86_64-unknown-linux-musl
```

When I run `ldd` on the resulting executable I get `not a dynamic executable` which is what I expect. 

When I run `file` on the resulting executable I get:

```
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

Again, what I expect.

When I just run the executable by itself, it makes the connection to Mosquitto with no problem but when I attempt to run it from within a Docker container based on `scratch` as the base layer, it fails with the `Paho(-2)` error. Here is the code where this fails:

```rust
    // Create the MQTT client. Use an ID for a persistent session.
    let create_opts = mqtt::CreateOptionsBuilder::new()
        .server_uri(host)
        .client_id(client_id)
        .finalize();

    // Create the MQTT client connection
    let mut mqtt_cli: mqtt::AsyncClient;
    let r = mqtt::AsyncClient::new(create_opts);
    match r {
        Ok(c) => {
            mqtt_cli = c;
            if is_debug {
                println!("MQTT client created");
            }
        }
        Err(e) => {
            println!("Error creating the client: {:?}", e);
            std::process::exit(1);
        }
    }
```

I see `Error creating the client: Paho(-2)` in the container's log. I even tried adding `--network=host` to my `docker run` command thinking that maybe my app couldn't reach outside of the container but that didn't work either.

Finally found the offending problem. I had the following line in my `Dockerfile`:

`USER 1000`

Apparently the `paho-mqtt` library doesn't like this. I was trying to not run as `root` inside of the container. I also have a `postgres` connection in the application and it had no problem with the `USER 1000` line in the `Dockerfile`. I was able to successfully make the connection to my database before the connection attempt to Mosquitto that you see in the code snippet above.

**Comment by fpagliughi** [comment]
Sorry, I _really_ need to do something about making the Paho internal errors a little more descriptive!

Paho(-2)  is a "Persistence Error". The default file persistence is probably trying to create the persistence directory and doesn't have the proper file permissions. If you don't want persistence, you can add `.persistence(None)` to your create options, like:

```
    let create_opts = mqtt::CreateOptionsBuilder::new()
        .server_uri(host)
        .client_id(client_id)
        .persistence(None)
        .finalize();
```

If you would prefer to use the default persistence, you would need to make sure you have permission to create an populate a directory under the CWD for the application.

**Comment by dwaynebradley** [comment]
Thanks @fpagliughi! That makes sense based off of what I was seeing and trying to do. At least this is documented here now. :-)
