### ISSUE TITLE
persistence_ptr is a raw pointer why I believe it could be a Box

### ISSUE THREAD

**Issue by siscia** [eclipse/paho.mqtt.rust#12]
Hi,

I was looking into the PR #11 and I noticed the drop called inside a drop, which I believe is unnecessary: https://github.com/eclipse/paho.mqtt.rust/blob/184e1a6eb390013a3d201a3d66c6271822909213/src/async_client.rs#L928

Similarly, I was trying to figure out why that drop and I realized that persistence_ptr is a raw pointer in AsyncClient: (https://github.com/eclipse/paho.mqtt.rust/blob/184e1a6eb390013a3d201a3d66c6271822909213/src/async_client.rs#L367), while I believe it could be a simple Box, simplifying a lot the drop and removing a source of unsafeness.

Is there a reason why we use that raw pointer? Maybe is something I am overlooking... I can provide a PR to make it a Box, if you guys need.

**Comment by fpagliughi** [comment]
I will have a better look at this and make a decision before this next release.

**Comment by fpagliughi** [comment]
Thanks, @siscia . Clearly the persistence code was confusing and needed to be cleaned up. In particular, the gory details certainly did not belong in the AsyncClient object.

I'm on the fence as to whether I would always keep a Boxed object in the Rust code in similar situations where a C lib needs to keep a context pointer. Sometimes, it would probably be easier to consume/leak the object with `Box::into_raw()` and then recover and drop it later. But I'll give this way a try for now and see how it "feels".

Either way we do it, for Paho C persistence, we need to keep two objects alive:
 - The Rust user persistence object.
 - The `ffi::MQTTClient_persistence` object containing the context pointer and callback pointer table.

These two now live in a `UserPersistence` struct, and the AsyncClient keeps one of them as a boxed option:
```
    // The user persistence (if any)
    user_persistence: Option<Box<UserPersistence>>
```

This is currently in the "develop" branch.
