### ISSUE TITLE
Upgrade to support paho.mqtt.c v1.3.9

### ISSUE THREAD

**Issue by svanharmelen** [eclipse/paho.mqtt.rust#128]
I noticed a new bugfix release was cut and it looks like it didn't change or add any struct options. So could it "just" be updated, or do you think it needs additional changes in the Rust binding code?

**Comment by fpagliughi** [comment]
Oh, I hadn't seen that it was released. If there aren't any changes to the C structs, then it _should_ be able to compile and link the new version without any other changes. That would require an update to the -sys crate. But if we're going to do that, it would probably be worth pushing out the other little fixes sitting in the main crate.

**Comment by icraggs** [comment]
1.3.9 should have no external changes, just internal fixes.  That was my intention anyway :-)

**Comment by fpagliughi** [comment]
OK. Great. 

Rust is a little more strict in that _any_ change to a struct, even just adding a field to the end, is considered a breaking change. But it's fine either way. The Rust library is actually two separate "crates"; a low-level _-sys_ crate which wraps the C library, and a higher-level one to provide a "safe" Rust API. The _-sys_ crate automatically downloads, builds, and links in the C library, so we need to update the build for the new C version anyway.

**Comment by fpagliughi** [comment]
Yes, I will be back on moving this forward within the next few days...
