### ISSUE TITLE
can set_payload function be added to MessageBuilder class

### ISSUE THREAD

**Issue by goutham2688** [eclipse/paho.mqtt.rust#139]
type of issue: improvement or how to, if the functionality doesn't exist already.

issue: in certain cases I'd be receiving a mqtt message, and in response I'll be updating the status of the request in multiple publishes to the same topic.
I feel instead of initializing the message via  MessageBuilder, I'd like to update just the payload. 
and use the same msg structure multiple sense.

current working:
``` rust
// Create a message and publish it
let msg = mqtt::MessageBuilder::new()
    .topic("test")
    .payload("test1")
    .qos(1)
    .finalize();

if let Err(e) = cli.publish(msg) {
    println!("Error sending message: {:?}", e);
}

let msg = mqtt::MessageBuilder::new()
    .topic("test")
    .payload("test2")
    .qos(1)
    .finalize();

if let Err(e) = cli.publish(msg) {
    println!("Error sending message: {:?}", e);
}
```

proposed look:
``` rust
let msg = mqtt::MessageBuilder::new()
    .topic("test")
    .payload("test1")
    .qos(1)
    .finalize();

if let Err(e) = cli.publish(msg) {
    println!("Error sending message: {:?}", e);
} 

msg.set_payload("test2")

if let Err(e) = cli.publish(msg) {
    println!("Error sending message: {:?}", e);
}
```

**Comment by fpagliughi** [comment]
Added `SyncTopic` for this. Feel free to reopen this issue if there are any further problems.
