### ISSUE TITLE
Feature request: Public interface to retrieve client ID from initialised client

### ISSUE THREAD

**Issue by cph-w** [eclipse/paho.mqtt.rust#155]
Once a client is initialised the client ID is persisted and accessible only on the inner client. Users of the client may wish to retrieve the client ID without wrapping the object with another means of storing the data or using the context, and as such a public interface to retrieve the client ID is helpful.

**Comment by cph-w** [comment]
I've submitted PR https://github.com/eclipse/paho.mqtt.rust/pull/154 for this feature

**Comment by fpagliughi** [comment]
Thanks for the PR. Apologies for the delay. Been busy on the Paho C++ client this week.
But it looks good. Merged.
