### ISSUE TITLE
Async Client invalid access

### ISSUE THREAD

**Issue by Visic** [eclipse/paho.mqtt.rust#159]
Using the ConnectOptionsBuilder.automatic_reconnect with an async client results in an invalid access error on line 304 of token.rs

My current test is set up to fail to connect to a broker and I do see the initial connection failure reported correctly, additionally, taking out the automatic_reconnect seems to work as well.

`paho-mqtt = { version = "0.11.1", default-features = false, features = ["bundled", "build_bindgen"] }`

On windows 10 (nightly-x86_64-pc-windows-msvc   rustc 1.63.0-nightly) , no cross compilation.

**Comment by fpagliughi** [comment]
Thanks! I'll have a look.

**Comment by fpagliughi** [comment]
This is manifesting in a few ways and was finally tracked down to an issue in the C library. I'll get it fix and updated here as soon as something lands upstream.

**Comment by fpagliughi** [comment]
It looks like this is fixed with the upcoming v0.12.3 release. At least I can't recreate it in testing.
If you still see it with that version, please feel free to reopen.
