### ISSUE TITLE
`None` value for `paho_mqtt::create_options::CreateOptionsBuilder persistance`

### ISSUE THREAD

**Issue by Joseda8** [eclipse/paho.mqtt.rust#163]
The documentation for [CreateOptionsBuilder method.persistence](https://docs.rs/paho-mqtt/latest/paho_mqtt/create_options/struct.CreateOptionsBuilder.html#method.persistence) indicates that setting this value as `None` will improve the performance, but ending up with a less reliable system. 

Could someone elaborate on this? Please. Under which circumstances should I consider setting this to `None`?

**Comment by fpagliughi** [comment]
If you use file persistence, then any message sent with QoS > 0 will be saved to disk until it is acknowledged. If your app crashes and restarts, the library will find the un-completed messages and attempt to re-send them automatically.

For each of those messages, there's the overhead of writing them to disk, and then finding and erasing them when ACK'ed. For many applications this is overkill. Moreover, for embedded apps (like on an embedded Linux gateway), this can contribute to thrashing the Flask chips and wear them out prematurely.

So to avoid this, setting Persistence to None just keeps the in-flight messages in RAM. If the program crashes, however, the messages may be lost.
