### ISSUE TITLE
Request for 0.9.2 Patch Release

### ISSUE THREAD

**Issue by CodeTako** [eclipse/paho.mqtt.rust#171]
The API changes to streams in version 0.10 and beyond are causing issues for our libraries when we try to upgrade. Would it be possible to get a patch release to version 0.9 that incorporates the fix to #148? We're currently using 0.9.1

**Comment by fpagliughi** [comment]
Yeah, that seems easy enough. Give me a couple days...

**Comment by CodeTako** [comment]
Thanks!

**Comment by fpagliughi** [comment]
No worries. I appreciate you reporting that bug. I published the release, but it's the first time I tried publishing off an old branch, so feel free to re-open this ticket and report any problems if I messed it up!

**Comment by CodeTako** [comment]
Works beautifully! Thank you!
