### ISSUE TITLE
compiling example dyn_subscribe

### ISSUE THREAD

**Issue by thepperson** [eclipse/paho.mqtt.rust#172]
I am trying to compile the dyn_sbuscribe example, but am running into a linking issue. I am using MSVC for the build.

note: libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetProcessWindowStation referenced in function OPENSSL_isservice  
          libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetUserObjectInformationW referenced in function OPENSSL_isservice          libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_MessageBoxW referenced in function OPENSSL_showfatal

**Comment by fpagliughi** [comment]
Which version of...
- Windows
- MSVC compiler (Visual Studio?)
- OpenSSL Library?

**Comment by thepperson** [comment]
Windows 10, Visual Studio 2022, openssl 3.0.5 (installed with vcpkg)

**Comment by fpagliughi** [comment]
Thanks. I'll try the Windows builds this week.

A quick Internet search finds a similar complaint in another Rust library:
https://github.com/OSSystems/compress-tools-rs/issues/57

Their fix seems to be manually linking in the Windows library in `build.rs`, like:
```
println!("cargo:rustc-link-lib=User32");
```
I wonder if that would work for us.

**Comment by fpagliughi** [comment]
I wasn't able to recreate the problem - possibly because I haven't upgraded to VS 2022 yet (?). But I added the line to the build file to link in User32 on Windows. Hopefully that helps.
