### ISSUE TITLE
Can not build Rust Project with paho-mqtt-sys library on Mac os Apple M1 Pro

### ISSUE THREAD

**Issue by burak0206** [eclipse/paho.mqtt.rust#174]
Hi all,
I am developing a rust web project using the M1 pro chipset. I installed mosquitto with brew and paho.mqtt.c with macports. I added paho-mqtt-sys and paho-mqtt. Before that, application can be built. However if I add paho-mqtt libraries, It gives an error when I call cargo build --target x86_64-apple-darwin.

What should I do to fix the error?

Error:

<img width="790" alt="Ekran Resmi 2022-11-20 18 27 11" src="https://user-images.githubusercontent.com/3257650/202916642-3c8d0667-c37e-4502-a7ae-1cac1ffec40d.png">

**Comment by appelgriebsch** [comment]
Interestingly the generated libpaho-mqtt3as.a is a `fat` binary already....

```
target/release/build/paho-mqtt-sys-78ae08bf9e76abb2/out/lib/libpaho-mqtt3as.a: Mach-O universal binary with 2 architectures: [x86_64:current ar archive random librarycurrent ar archive random library] [arm64:current ar archive random librarycurrent ar archive random library]
target/release/build/paho-mqtt-sys-78ae08bf9e76abb2/out/lib/libpaho-mqtt3as.a (for architecture x86_64):	current ar archive random library
target/release/build/paho-mqtt-sys-78ae08bf9e76abb2/out/lib/libpaho-mqtt3as.a (for architecture arm64):	current ar archive random library
```

Could that be the issue?

**Comment by appelgriebsch** [comment]
there was a recent PR merged in rust... https://github.com/rust-lang/rust/pull/98736

**Comment by appelgriebsch** [comment]
checked it with the beta toolchain just now. it builds for both architectures on my M1 :)

**Comment by burak0206** [comment]
good news!, I will try it @appelgriebsch

**Comment by appelgriebsch** [comment]
> I tried to these instructions set and I can compile. thank you @appelgriebsch
> 
>     1. rustup update && rustup update beta && rustup install beta
> 
>     2. rustup default beta-aarch64-apple-darwin
> 
>     3. rustup target add x86_64-apple-darwin
> 
>     4. cargo clean && cargo build --target x86_64-apple-darwin

instead of making the `beta` channel the default one you can also prefix the `cargo` commands with the channel to be used:

```
cargo +beta target add x86_64-apple-darwin
cargo +beta build --target x86_64-apple-darwin
```

**Comment by appelgriebsch** [comment]
You can then use the `lipo` command to combine both binaries into a single universal (fat) binary like so:

```
lipo -create -arch arm64 <path-to-aarch64-apple-darwin-binary> -arch x86_64 <path-to-x86_64-apple-darwin-binary> -o <path-to-universal-binary>
```

Benefit: this universal binary works for both architectures.

**Comment by burak0206** [comment]
Hi @fpagliughi ,

yes it can be nice, I can add if you want. but I don't know which one is the best. I think @appelgriebsch knows better than me.

**Comment by appelgriebsch** [comment]
Sorry for radio silence. Was a bit busy lately. Will provide a PR for the README update on the coming weekend.
