### ISSUE TITLE
mqtt will create a diretory when connection, how to avoid?

### ISSUE THREAD

**Issue by heliping** [eclipse/paho.mqtt.rust#178]
I found when created a mqtt client, there would be created a directory.
I want to create many client, so the direcotries so many that take me unease.
Is there any ways to avoid this?

![image](https://user-images.githubusercontent.com/24326525/205235031-5e5614be-ee5c-43fb-8521-40be30331c5e.png)

**Comment by fpagliughi** [comment]
These contain the persistence data for the open connection, which uses File persistence by default. If you don't want to use persistence at all, specify `PersistenceType::None` in the `CreateOptions` when you create the client.

If you do want persistence, but don't want to make a separate directory per client, you can always create a custom persistence solution.

**Comment by heliping** [comment]
got it!  thans, bro.
