### ISSUE TITLE
Force AsyncClient to cancel a connect attempt so that it can be dropped

### ISSUE THREAD

**Issue by tross-skybell** [eclipse/paho.mqtt.rust#180]
I timeout waiting to connect but I cannot exit the function until the connect times out and I don't seem to be able to control that timeout.

`
  let conn_opts = mqtt::ConnectOptionsBuilder::new()
      .ssl_options(ssl_opts)
      .connect_timeout(time::Duration::from_millis(5000))
      .keep_alive_interval(time::Duration::from_secs(30))
      .automatic_reconnect(time::Duration::from_millis(500), time::Duration::from_secs(30))
      .clean_session(true)
      .clean_start(false)
      .finalize();
  
  let result = mqtt_client.connect(conn_opts).wait_for(time::Duration::from_millis(5000));
  match result {
      Ok(_) => {
            },
      Err(e) => {
          //log_Info!(log::Module::Cloud, "Dropping mqtt_client");
          drop(mqtt_client);
          //log_Info!(log::Module::Cloud, "Continue now");
          continue 'aws_main;
      },
        }  
`

In the above example (in the case of failure to connect) there are 60 seconds between the drop and continue. I assume that is because the connection is still waiting to time out, but the timeout should just be 5 seconds. I can't seem to find any other timers that would cause this issue.

Is there something obvious I am missing?

**Comment by tross-skybell** [comment]
Update. I found the source of the problem on my system. The random seed wasn't yet initialized at boot so any openssl call hangs until it can get a random number.

This probably means that there isn't anything paho mqtt can do since it is stuck pending.

**Comment by fpagliughi** [comment]
I think you're right that this can't really be fixed easily if it's in a system call.
