### ISSUE TITLE
doesn't compile on Ubuntu installed on Jetson

### ISSUE THREAD

**Issue by agiordana** [eclipse/paho.mqtt.rust#185]
I'm trying to use mqtt on jetson nano. Cargo fail running cmake because of the flag --parallel not supported.
looking in the code I've found paho-mqtt-sys/cCargo.toml, where there is a comment about using dependencies from cmake crate v0.1.45 because the fleg --parallel is not supported everywery.
As a matter of fact the dependency in the build-dependencies is set to v0.1.48!

**Comment by fpagliughi** [comment]
OK. It looks like that PR 146 didn't make it into a release until cmake crate v0.1.49. But I had accidentally let the version pinned to the one specified even after I updated it.

I will do a new release of the -sys crate later today, with the fix, and then it should build on your Nano.

**Comment by agiordana** [comment]
As a matter of fact, I've found the file
~/.cargo/git/checkouts/paho.mqtt.rust-44b07fd42c95bba6/eee12c6/paho-mqtt-sys/Cargo.toml
and I changed the
the version: cmake = { version = "=0.1.45", optional = true } instead of
0.1.48, and everything worked perfectly.
Thanks for your quick answer.
Attilio Giordana

**Comment by fpagliughi** [comment]
You should also be able to move it forward to the latest release:

`cmake = { version = "0.1.49", optional = true }  `

(get rid of the equals while you’re at it) and that will work.  It that’s in the release I just put out, so just run `cargo update` and that should work,too.

I’ll close this, but feel free to re-open if there’s any other problem.

**Comment by agiordana** [comment]
Many thanks
Attilio
