### ISSUE TITLE
Is there support for mTLS?

### ISSUE THREAD

**Issue by dulataldazharov** [eclipse/paho.mqtt.rust#187]
Is there a way to specify mTLS options when connecting to a broker?
For example, the mosquitto client in Rust has it: https://docs.rs/mosquitto-client/latest/mosquitto_client/struct.Mosquitto.html#method.tls_set
Is there something similar in the API of this library?

**Comment by fpagliughi** [comment]
Yes. Use the `SslOptions` and add them to the `ConnectOptions`. Although it uses the term SSL, it’s really TLS

**Comment by dulataldazharov** [comment]
Thanks a lot!
