### ISSUE TITLE
Please bump bindgen build dependency

### ISSUE THREAD

**Issue by stintel** [eclipse/paho.mqtt.rust#194]
After hitting a segfault I tried enabling the build_bindgen feature, but that didn't work because of a dependency conflict.

$ cargo add paho_mqtt --features build_bindgen
    Updating crates.io index
warning: translating `paho_mqtt` to `paho-mqtt`
      Adding paho-mqtt v0.12.0 to dependencies.
             Features:
             + build_bindgen
             + bundled
             + ssl
             - vendored-ssl
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.52.0`
    ... which satisfies dependency `bindgen = "^0.52"` of package `paho-mqtt-sys v0.8.0`
    ... which satisfies dependency `paho-mqtt-sys = "^0.8.0"` (locked to 0.8.0) of package `paho-mqtt v0.12.0`
    ... which satisfies dependency `paho-mqtt = "^0.12.0"` (locked to 0.12.0) of package `auditd-forwarder v0.1.0 (/home/stijn/projects/auditd-forwarder)`
versions that meet the requirements `^0.28.0` are: 0.28.1, 0.28.0

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v1.6.0`
    ... which satisfies dependency `clang-sys = "^1"` (locked to 1.6.0) of package `bindgen v0.64.0`
    ... which satisfies dependency `bindgen = ">=0.56"` (locked to 0.64.0) of package `laurel v0.5.1`
    ... which satisfies dependency `laurel = "^0.5.1"` (locked to 0.5.1) of package `auditd-forwarder v0.1.0 (/home/stijn/projects/auditd-forwarder)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='clang-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `clang-sys` which could resolve this conflict

**Comment by fpagliughi** [comment]
Will do. Yeah, that's pretty old.

**Comment by fpagliughi** [comment]
I verified the old version was broken for me too, and bumped it to the latest, v0.64. That seems to work for me on Ubuntu 20.04.
