### ISSUE TITLE
if subscribe with a nonexist topic failed, then connection loss

### ISSUE THREAD

**Issue by voididea** [eclipse/paho.mqtt.rust#198]
if subscribe with a nonexist topic failed, then connection loss
expects: subscribe failures should not influence the client connection

**Comment by fpagliughi** [comment]
What do you mean by "nonexist topic"? One that has never been published? On that is blank, "" ?

**Comment by voididea** [comment]
> What do you mean by "nonexist topic"? One that has never been published? On that is blank, "" ?

had figure out, it was mqtt server side who close the connection,

**Comment by voididea** [comment]
close
