### ISSUE TITLE
Published message not received on subscriber

### ISSUE THREAD

**Issue by harshakhmk** [eclipse/paho.mqtt.rust#220]
Hi, I am testing few examples mentioned here with a publisher and subscriber https://github.com/eclipse/paho.mqtt.rust/blob/master/examples/sync_publish.rs
https://github.com/eclipse/paho.mqtt.rust/blob/master/examples/sync_consume.rs
There was no build issue with code, but publisher is successfully sending message, but subscriber is not receiving any message 
On closer inspection, I have seen publisher default connection to v3 broker and subscriber got connected to v4 version, I tried changing the version of mqtt broker in Client, however I was getting error like it is not supported to set the version

**Comment by fpagliughi** [comment]
Closing from lack of activity.
