### ISSUE TITLE
Is paho mqtt supports Rustls ?

### ISSUE THREAD

**Issue by sarath3192** [eclipse/paho.mqtt.rust#222]
If yes, please provide me the details, thank you in advance.

**Comment by fpagliughi** [comment]
No. At this time, the Rust library is just a wrapper around the Paho C library. The C library handles the network communications, and it uses OpenSSL.

There is a plan to eventually convert this to 100% Rust, but that work is still seeking funding and may not start for a while.

**Comment by fpagliughi** [comment]
Most of the Paho libraries already support using TLS. There is nothing to add. The Paho C, C++, and Rust libraries all share the base C library, so have identical features for connecting to a broker. Currently they already support TLS, but they use the OpenSSL implementation. 

In addition to a straight TLS connection, you can also use WebSockets either unsecure or over TLS.

For s straight TLS connection, see the `ssl_publish` example in this repo:
https://github.com/eclipse/paho.mqtt.rust/blob/master/examples/ssl_publish.rs

**Comment by fpagliughi** [comment]
I assume the question is answered? If not, feel fee to re-open and expand.
