### ISSUE TITLE
Use "cross" for cross compiling to multiple platforms

### ISSUE THREAD

**Issue by dwaynebradley** [eclipse/paho.mqtt.rust#28]
The rust-embedded team has created ["cross"](https://github.com/rust-embedded/cross) that allows easy cross compilation to multiple platforms. Maybe look into using it for the cross-compiling of the MQTT crate.

**Comment by fpagliughi** [comment]
Wow. Cool. Thanks. I will definitely have a look.

**Comment by fpagliughi** [comment]
Finally, with the new `openssl-sys` support added, it's easy to use "cross". I added some basic instruction to the README.
