### ISSUE TITLE
macos mojave build issue

### ISSUE THREAD

**Issue by ckalas** [eclipse/paho.mqtt.rust#32]
running `cargo build --examples` fails with this error which I can't for the life of me solve.

`  = note: Undefined symbols for architecture x86_64:
            "_X509_check_host", referenced from:
                _SSLSocket_connect in libpaho_mqtt_sys-2049afa2e25264ee.rlib(SSLSocket.c.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I have openssl installed with homebrew and I have no issues with other libraries using it. my python binding of Paho works fine as well

**Comment by fpagliughi** [comment]
I don't personally use a Mac, so I'm of no help here. Anyone else?

**Comment by ckalas** [comment]
Looking through my history I apparently resolved this by setting the following openssl env variables:

```
 1936  export OPENSSL_ROOT_DIR=/usr/local/ssl
 1937  export OPENSSL_LIBRARIES=/usr/local/ssl
 1938  cargo build --examples
```
