### ISSUE TITLE
Does not compile on Fedora 29

### ISSUE THREAD

**Issue by Mebus** [eclipse/paho.mqtt.rust#34]
Hallo,

sadly this doesn't compile for me on Fedora 29. See attached file. There seems to be a problem with OpenSSL:

[error.txt](https://github.com/eclipse/paho.mqtt.rust/files/2921975/error.txt)

Mebus

**Comment by fpagliughi** [comment]
OK. This appears to be an issue with the underlying Paho C library. Can you verify the version of OpenSSL you're using. It appears that Fedora 29 packages openssl-1.1.1a or b

**Comment by Mebus** [comment]
This is what dnf tells me about the openssl package:

```
Name         : openssl
Epoch        : 1
Version      : 1.1.1a
Release      : 1.fc29
Architecture : x86_64
Size         : 1.1 M
Quelle       : openssl-1.1.1a-1.fc29.src.rpm
Repository   : @System
Aus Paketque : updates
Summary      : Utilities from the general purpose cryptography library with TLS implementation
URL          : http://www.openssl.org/
Lizenz       : OpenSSL
Description  : The OpenSSL toolkit provides support for secure communications between
             : machines. OpenSSL includes a certificate management tool and shared
             : libraries which provide various cryptographic algorithms and
             : protocols.
```

Mebus

**Comment by pashinov** [comment]
Fedora 30 has a same problem

**Comment by fpagliughi** [comment]
OK. There's a new release of the Paho C library that just came out a week ago. Maybe that fixes it. 
Either way, I plan to get a new release of the Rust client out that uses it.

**Comment by pashinov** [comment]
Thanks for reply, I am going to look forward new release and hope it will be fixed problem

**Comment by fpagliughi** [comment]
The release may not be for a few weeks, as I need to get the Paho C++ library out the door first.

But I just updated the 'develop' branch to make the -sys crate to wrap and build the latest Paho 1.3.1 library. It's quite untested at the moment, but I would love some feedback as to whether it fixes this issue. If anyone could try it and report back, that would be great.

If it doesn't work, just check whether it properly pulled the latest version from the Git submodule:
```
$ cd paho.mqtt.rust
$ grep PAHO_VERSION paho-mqtt-sys/paho.mqtt.c/CMakeLists.txt 
SET(PAHO_VERSION_MAJOR 1)
SET(PAHO_VERSION_MINOR 3)
SET(PAHO_VERSION_PATCH 1)    <- This should be "1", not "0"
...
```

**Comment by pashinov** [comment]
It works, thanks for temporary decision!
