### ISSUE TITLE
mqtt client is creating empty folders

### ISSUE THREAD

**Issue by mfrlin** [eclipse/paho.mqtt.rust#35]
Folders are created with the name `<client_id>-<host>-<port>`. This is especially annoying when your client id is dynamic so a lot of folders get created. Also in my case the folders are empty so are they really needed? What happens on read only filesystems?

**Comment by fpagliughi** [comment]
By default, the library uses file-based persistence for inflight messages with a QoS >= 1.  That means if your client application crashes - or even if the whole system goes down - while messages are being sent to the broker, there's a good chance that when you're app restarts, the messages will automatically be recovered by the client and re-sent, automatically.

If that's not the behavior that you want, then you can change it when you create the client. The "persistence" field of the _create_options_ lets you set it. You can set the _PersistenceType_ to _None_, in which case you turn it off completely. Or you can define the behavior yourself with _User_ persistence.

One thing I regularly do on embedded Linux systems is use a local Redis server (in the device) as the user persistence store. That way it doesn't thrash the flash chips, but the messages are still persisted outside my application in case it crashes. I have a side project demonstrating this:
https://github.com/fpagliughi/mqtt.rust.redis

**Comment by mfrlin** [comment]
Thank you for explaining. I see now that it is documented in the source so I should have looked harder.
