### ISSUE TITLE
Cannot pass `OPENSSL_SEARCH_PATH` needed for cross-compilation

### ISSUE THREAD

**Issue by drasko** [eclipse/paho.mqtt.rust#38]
Paho MQTT lib demands `OPENSSL_SEARCH_PATH` env variable as described [here](https://github.com/eclipse/paho.mqtt.c/tree/9f715d0862a8e16099b5837c4e53a1bf6a6a0675#build-instructions-for-gnu-make) in order to pick correct cross-compiled OpenSSL lib.

However, looking at [here](https://github.com/eclipse/paho.mqtt.rust/blob/master/paho-mqtt-sys/build.rs#L149) it looks that it is impossible to pass this information to a build today.

Without this possibility, it is impossible to execute cross-compile.

**Comment by fpagliughi** [comment]
Makes sense.

**Comment by fpagliughi** [comment]
Fixed with PR #40
