### ISSUE TITLE
Not receiving None on disconnected

### ISSUE THREAD

**Issue by rcastill** [eclipse/paho.mqtt.rust#48]
Related to #37

In [paho.mqtt.rust/examples/sync_consume.rs:210](https://github.com/eclipse/paho.mqtt.rust/blob/4f1aa7497b8fe29c79db6038e4f477cbacfa4eee/src/async_client.rs#L210), it seems that `None` is sent when disconnection occurs.

But when I manually disconnect the client (`client.disconnect(None)`), I rather get an `Err()` when calling on the receiver's (spawned with `client.start_consuming()`) `recv()` method instead of `Ok(None)`.

Is that intended?

**Comment by fpagliughi** [comment]
No, I can't say that's intended. I'll have a look.

**Comment by fpagliughi** [comment]
OK. It looks like we don't get an on_connection_lost() callback from a manual disconnect. This makes perfect sense. So we just need to manually push a _None_ into the message stream from within the call to `disconnect()`

**Comment by fpagliughi** [comment]
Found another one like this... #61
