### ISSUE TITLE
Support for on_connect callback

### ISSUE THREAD

**Issue by rcastill** [eclipse/paho.mqtt.rust#49]
There is already in the code a function not currently used for this: https://github.com/eclipse/paho.mqtt.rust/blob/4f1aa7497b8fe29c79db6038e4f477cbacfa4eee/src/async_client.rs#L190

The comments say:
> We currently don't use this for anything. Rather connection completion is tracked through a token.

But there is a case in which I think this function is still useful. `ConnectOptions` allow for automatic reconnection. If disconnection occurs, the client **does** reconnect but subscriptions are lost, therefore, all subscriptions should be managed `on_connect`.

The workaround I'm using now is that when I detect disconnection I call `cli.reconnect()` and resubscribe to any topic subscribed before disconnection.

**Comment by fpagliughi** [comment]
Agreed. I added this callback into the Paho C++ lib. I will add it here as well.
