### ISSUE TITLE
Not sure how to work with websockets?

### ISSUE THREAD

**Issue by laurentva** [eclipse/paho.mqtt.rust#50]
Hey Frank, love the work you've been doing on this.

I'm working on making a Rust example for our MQTT datastream, but I get an empty error when trying to create an async client, I think it's because the protocol wss does not get recognized. Any tips?

```rust
   let host = env::args().skip(1).next().unwrap_or(
        "wss://mqtt.cloud.pozyxlabs.com:443".to_string()
    );

    // Create the client. Use an ID for a persistent session.
    // A real system should try harder to use a unique ID.
    let mut rng = rand::thread_rng();
    let random_id: u16 = rng.gen();
    let create_options = mqtt::CreateOptionsBuilder::new()
        .server_uri(host)
        .client_id(format!("pozyx-rust-mqtt-{:?}", random_id))
        .finalize();

    // Create the client connection
    let mut cli = mqtt::AsyncClient::new(create_options).unwrap_or_else(|e| {
        println!("Error creating the client: {:?}", e);
        process::exit(1);
    });
```

Results in
Error creating the client: 

Kind regards,

**Comment by fpagliughi** [comment]
Hi. The WebSocket support was done entirely in the underlying Paho C client... and we got it for free in the Rust wrapper! It was very nice.

There are a (at least) two things that are required:

1. You need to make sure you're wrapped around Paho C v1.3.0 or later. The current release of Rust Client v0.5 does this, but earlier versions did not.
(Side note: There are some known bugs in Paho C v1.3.0. A release of 1.3.1 is recently available, with some initial support in the 'develop' branch of this Rust repo).

2. You need to make sure web socket support is properly compiled and configured into the broker that you're using. I've only tested this with a recent version of Mosquitto, but I had to go out ogf my way to compile and configure it properly.

3. If you're using the secure version of websockets (wss), maybe you need to set up certificates via SSL options to the connect call, or something like that? I can't remember, but I can check.

And apologies for the blank error message. Newer versions of the library will have better error messages, and when it moves to MQTT v5 (hopefully before the end of the year), it will improve even further.

**Comment by fpagliughi** [comment]
@laurentva Did you have any success figuring this out?

**Comment by laurentva** [comment]
Hey @fpagliughi,

Unfortunately didn't find the extra time at work yet to find a breakthrough. I'd love to figure this out at some point, but I understand if you'd want to close the issue. I got stuck on adding the SSL certificates in Rust, there seem to be a couple of options but making them work together is something I didn't get functional yet. 

Kind regards,

**Comment by laurentva** [comment]
PS Happy Holidays :smile: :christmas_tree:

**Comment by fpagliughi** [comment]
Thanks. No worries. Keep the issue open until we find a solution.
I may have more time to look at it in the near future. Plus the C lib has had some updates recently, including web sockets. So there may be some help on that end.

Also, we may get more information using the logging in either the C lib or Rust lib. Set the environment variables:
```
  export MQTT_C_CLIENT_TRACE=ON
  export MQTT_C_CLIENT_TRACE_LEVEL=MEDIUM
  export RUST_LOG=DEBUG
```
and then run your app and post the output here...

**Comment by fpagliughi** [comment]
Any progress on this?
