### ISSUE TITLE
Segmentation fault on subscribe_many with single topic

### ISSUE THREAD

**Issue by tobdub** [eclipse/paho.mqtt.rust#51]
subscribe_many segfaults when called with a slice containing a single topic.
Using the async client with futures.
master branch: 4f1aa749
Ubuntu 18.04, rust 1.37

**Comment by fpagliughi** [comment]
Thanks for the report. I'll take a look.

**Comment by fpagliughi** [comment]
Sorry for the delay... I think I see it. For some reason the C lib makes a distinction between "subscribe" and "subscribeMany", putting the responses in different places. But then, on the return, it drops the distinction if it was a single item, and puts the response in a different place.

Thanks again. I'll get a fix in.
