### ISSUE TITLE
Segmentation fault in Arm platform

### ISSUE THREAD

**Issue by richardchey** [eclipse/paho.mqtt.rust#55]
rust: 1.39
target: armv7-unknown-linux-gnueabihf
host: Ubuntu 18.04.3 LTS
code: examples/async_subscribe.rs

![图片](https://user-images.githubusercontent.com/6816901/69058283-564f8400-0a4e-11ea-9a0e-d7e3a80f3372.png)

**Comment by fpagliughi** [comment]
Which version (or branch) of this crate are you using?

**Comment by richardchey** [comment]
0.6.0 from crates.io

**Comment by fpagliughi** [comment]
@richardchey  Did you find a resolution? I will be working on this library for the next few days.

**Comment by richardchey** [comment]
I tried to enable the "build_bindgen" feature, and then it's done.

![图片](https://user-images.githubusercontent.com/6816901/69838401-60635500-128e-11ea-9e8b-b29ecd748675.png)

**Comment by fpagliughi** [comment]
Oh, OK. I was worried about that at first - that the bindings would be different for different targets. But when I first tried it, everything worked fine. I should probably put up a warning about this in the README, or better yet, put up pre-built bindings for multiple targets.

**Comment by richardchey** [comment]
OK. Thanks for your work.
