### ISSUE TITLE
Support Rust async-await and Futures 0.3

### ISSUE THREAD

**Issue by encombhat** [eclipse/paho.mqtt.rust#59]
Rust 1.39 now has stable async/await syntax. Would be good if Paho is updated to it.

**Comment by fpagliughi** [comment]
Ha. Yes. MQTT v5 first, though.

**Comment by fpagliughi** [comment]
Getting started on it this week!

**Comment by fpagliughi** [comment]
This is working in the `develop` branch. Should be released in v0.8 in a few weeks.

**Comment by fpagliughi** [comment]
...or a few months. But it got there.
