### ISSUE TITLE
option to disable server cert auth

### ISSUE THREAD

**Issue by patriques82** [eclipse/paho.mqtt.rust#64]
Hi currently there is no way to disable server cert authentication which we need to do at our workplace, I would like to add a function to the ssl_options module

```rust   
pub fn enable_server_cert_auth(&mut self, enable_server_cert_auth: bool) -> &mut SslOptionsBuilder {
    self.enable_server_cert_auth = enable_server_cert_auth;
    self
}
```
At the same time I could add some of the other tests that currently have todos in the same module

**Comment by patriques82** [comment]
Currently when I run with `enable_server_cert_auth(false)` to connect to a broker with mqtts enabled this does not allow me to connect:

> SSL not supported by Paho C library: SSL not supported by Paho C library to broker

So maybe something more than this is needed in order to make it work.

**Comment by fpagliughi** [comment]
Oh. It seems like your Paho C library was compiled without SSL support enabled. Unfortunately, that's the default for building it, and if you're building from sources, you need to enable it at compile time. For example, if you use CMake, you need to add `-DPAHO_WITH_SSL=ON`.

Then you need to link with the "secure" version of the library: *paho-mqtt3as.so* (or .a, .lib, .dll, etc). The "s" at the end of the base name indicates the version compiled with SSL.

**Comment by patriques82** [comment]
Yes that was it, did not read the documentation well enough. All I actually needed was to enable ssl feature and then 'export LIBRARY_PATH=/path/to/openssl/lib'. Would you like me to create the PR, or do you find the functionality redundant?

**Comment by fpagliughi** [comment]
No worries. I'll get the readme updated so it's a little clearer
