### ISSUE TITLE
Missing options to connect to AWS IoT Core using websockets

### ISSUE THREAD

**Issue by svanharmelen** [eclipse/paho.mqtt.rust#67]
It looks like this package is maybe missing some options to make it possible to connect to AWS IoT Core using websockets. I noticed that in the Python version there is a [ws_set_options](https://github.com/eclipse/paho.mqtt.python/blob/1eec03edf39128e461e6729694cf5d7c1959e5e4/src/paho/mqtt/client.py#L714) method, is there something similar for the Rust version that I might be overlooking?

When connecting to IoT Core using websockets it requires a few extra things (headers and a path). See here for a full Python example: https://github.com/eclipse/paho.mqtt.python/blob/master/examples/aws_iot.py

Would be great to understand if this can (or already is) supported in Rust too. Or (when not) if it should be possible to add it, as then I can maybe take a stab at it... Thanks!

**Comment by fpagliughi** [comment]
Unfortunately, the entire underlying connection and communications are handled by the C library, and we only get what they support (although, it's actually a lot!).  But it seems that they started adding some websocket options. I'll need to figure out how to wrap it, and whether it's sufficient, but it could be that this goes into v0.8 in a few months.

**Comment by fpagliughi** [comment]
As I mentioned, an option in the C lib appeared (outta nowhere) recently to set HTTP headers using name/value string pairs. I just added some code to set those values using the `ConnectOptionsBuilder::http:headers()` function. That's in the `develop` branch.

It takes a collection of string pairs, like:
```
let hdrs = [("name0", "val0"), ("name1", "val1"), ("name2", "val2")];
let opts = ConnectOptionsBuilder::new().http_headers(hdrs).finalize();
...
```

I haven't fully tested yet, and have no idea if this is sufficient to connect to AWS. I've never used Websockets to connect up to Amazon. But it would be interesting to port the AWS example from the Python library here and make sure it works.

If anyone gets around to trying this before I get to it, let me know if it works!

**Comment by svanharmelen** [comment]
Interesting! I have a few days off this week so will play around with it a bit as well. 

Not sure if I can make it work, but will let you know if I manage to achive anything noticable 😏

**Comment by adlers** [comment]
I'm attempting to connect to AWS using websockets as well. I built the proper headers but I get `Failed to connect: [-1] socket error` when attempting to connect. 

AWS requires a root certificate as well. In my case: `AmazonRootCA1.pem`. How do I make sure that the client connects using the proper SSL settings?

**Comment by fpagliughi** [comment]
I recently got a new AWS account, so I can start playing with this. I did manage to get a regular SSL/TLS connection working, but haven't tried websockets yet. The unfortunate thing is often the secure connection is created OK, but then the server decides to reject something in the connect packet, and since this is based on MQTT v3, it has no choice but to drop the connection with no reason as to what it doesn't like.

It would be awesome if the library would report separate errors for rejected TLS connection vs a rejected connect packet, but this all bubbles up from the underlying C library, so we'll need to bother them for a fix there.

**Comment by svanharmelen** [comment]
I found some time to work on this and I can report back that I was able to connect to AWS IoT Core using MQTT with a websocket over a proxy using the latest (v0.9.1) version 🎉 

If time permits I can maybe make a PR with a working example as inspiration for others. But have to find some time for it in the coming weeks, pretty busy with other stuff right now...
