### ISSUE TITLE
Add Reason Code and Properties to DisconnectOptions

### ISSUE THREAD

**Issue by berndv** [eclipse/paho.mqtt.rust#73]
To publish online/offline state changes of a client to subscribers reliably I want to use a last will message that denotes the client is now offline. The last will message must also be published by the broker in case of a proper disconnect of the clients.

I think MQTT 5 introduced "Disconnect Reason Codes" for that. See [1].

Please support at least reason code "4 Disconnect with Will Message" for my use case described above. 

(Workaround: In case of a proper disconnect, send offline message manually..)

[1] https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901208

**Comment by fpagliughi** [comment]
Yes, you're right! It looks like I forgot to add properties and a reason code to the disconnect options.

That's how I will fix it. I will allow you to set the reason code in the `DisconnectOptions` structure, probably via the `DisconnectOptionsBuilder`.

I'm working on an update right now. It's mostly for async/await support, but I also did miss a few things required for MQTT v5.

**Comment by fpagliughi** [comment]
OK. I pushed a fix for the reason code(s) to the develop branch. You will be able to st the code via the builder in one of two ways:
```
let opts = DisconnectOptionsBuilder::new()
    .reason_code(ReasonCode::DisconnectWithWillMessage)
    .finalize();
```
or
```
let opts = DisconnectOptionsBuilder::new()
    .publish_will_message()
    .finalize();
```
Those are equivalent.

I will get the properties in shortly.

**Comment by fpagliughi** [comment]
It's in and I even added it to the little chat example app, *mqttrs_chat.rs*:
https://github.com/eclipse/paho.mqtt.rust/blob/f3661714b3213726e9e3212b9e910739aadfa426/examples/mqttrs_chat.rs#L152-L157

**Comment by fpagliughi** [comment]
In v0.8
