### ISSUE TITLE
MacOS Build Error

### ISSUE THREAD

**Issue by gianghn** [eclipse/paho.mqtt.rust#75]
Hi, 

I user version 0.7.1. 

I tried to build the package and get the following error: 

➜  hello-rust git:(master) ✗ cargo build
   Compiling proc-macro2 v1.0.13
   Compiling unicode-xid v0.2.0
   Compiling cc v1.0.53
   Compiling autocfg v1.0.0
   Compiling syn v1.0.22
   Compiling libc v0.2.70
   Compiling log v0.4.8
   Compiling futures v0.1.29
   Compiling cfg-if v0.1.10
   Compiling num-traits v0.2.11
   Compiling cmake v0.1.44
   Compiling quote v1.0.6
   Compiling paho-mqtt-sys v0.3.0
   Compiling futures-timer v0.1.1
error: failed to run custom build command for `paho-mqtt-sys v0.3.0`

Caused by:
  process didn't exit successfully: `/Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-13c07ac71da3cec8/build-script-build` (exit code: 101)
--- stdout
debug:Running the bundled build for Paho C
cargo:rerun-if-changed=build.rs
running: "cmake" "/Users/macbook/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-sys-0.3.0/paho.mqtt.c/" "-DPAHO_BUILD_SHARED=off" "-DPAHO_BUILD_STATIC=on" "-DPAHO_ENABLE_TESTING=off" "-DPAHO_HIGH_PERFORMANCE=on" "-DPAHO_WITH_SSL=on" "-DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1g" "-DCMAKE_INSTALL_PREFIX=/Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out" "-DCMAKE_C_FLAGS= -fPIC -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version: 3.17.2
-- CMake system name: Darwin
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Timestamp is 2020-05-19T15:54:14Z
-- Found OpenSSL: /usr/local/Cellar/openssl@1.1/1.1.1g/lib/libcrypto.dylib (found version "1.1.1g")  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
Scanning dependencies of target common_obj_static
[  5%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTTime.c.o
[  5%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTProtocolClient.c.o
[  5%] Building C object src/CMakeFiles/common_obj_static.dir/Clients.c.o
[  7%] Building C object src/CMakeFiles/common_obj_static.dir/utf-8.c.o
[  9%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTPacket.c.o
[ 14%] Building C object src/CMakeFiles/common_obj_static.dir/Messages.c.o
[ 14%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTPacketOut.c.o
[ 16%] Building C object src/CMakeFiles/common_obj_static.dir/Tree.c.o
[ 16%] Building C object src/CMakeFiles/common_obj_static.dir/Socket.c.o
[ 18%] Building C object src/CMakeFiles/common_obj_static.dir/Log.c.o
Scanning dependencies of target common_ssl_obj_static
[ 20%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTTime.c.o
[ 22%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTPersistence.c.o
[ 24%] Building C object src/CMakeFiles/common_obj_static.dir/Thread.c.o
[ 25%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTProtocolClient.c.o
[ 27%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTProtocolOut.c.o
[ 29%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTPersistenceDefault.c.o
[ 31%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/Clients.c.o
[ 33%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/utf-8.c.o
[ 35%] Building C object src/CMakeFiles/common_obj_static.dir/SocketBuffer.c.o
[ 37%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTPacket.c.o
[ 38%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTPacketOut.c.o
[ 40%] Building C object src/CMakeFiles/common_obj_static.dir/LinkedList.c.o
[ 42%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/Messages.c.o
[ 44%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTProperties.c.o
[ 46%] Building C object src/CMakeFiles/common_obj_static.dir/MQTTReasonCodes.c.o
[ 48%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/Tree.c.o
[ 50%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/Socket.c.o
[ 51%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/Log.c.o
[ 53%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTPersistence.c.o
[ 55%] Building C object src/CMakeFiles/common_obj_static.dir/Base64.c.o
[ 57%] Building C object src/CMakeFiles/common_obj_static.dir/SHA1.c.o
[ 59%] Building C object src/CMakeFiles/common_obj_static.dir/WebSocket.c.o
[ 61%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/Thread.c.o
[ 62%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTProtocolOut.c.o
[ 64%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTPersistenceDefault.c.o
[ 66%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/SocketBuffer.c.o
[ 68%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/LinkedList.c.o
[ 70%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTProperties.c.o
[ 72%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/MQTTReasonCodes.c.o
[ 74%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/Base64.c.o
[ 75%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/SHA1.c.o
[ 77%] Building C object src/CMakeFiles/common_ssl_obj_static.dir/WebSocket.c.o
[ 77%] Built target common_obj_static
Scanning dependencies of target paho-mqtt3c-static
Scanning dependencies of target paho-mqtt3a-static
[ 79%] Building C object src/CMakeFiles/paho-mqtt3c-static.dir/MQTTClient.c.o
[ 81%] Building C object src/CMakeFiles/paho-mqtt3a-static.dir/MQTTAsync.c.o
[ 81%] Built target common_ssl_obj_static
[ 83%] Linking C static library libpaho-mqtt3c.a
Scanning dependencies of target paho-mqtt3as-static
Scanning dependencies of target paho-mqtt3cs-static
[ 85%] Linking C static library libpaho-mqtt3a.a
[ 90%] Building C object src/CMakeFiles/paho-mqtt3as-static.dir/MQTTAsync.c.o
[ 90%] Building C object src/CMakeFiles/paho-mqtt3cs-static.dir/SSLSocket.c.o
[ 90%] Building C object src/CMakeFiles/paho-mqtt3cs-static.dir/MQTTClient.c.o
[ 92%] Building C object src/CMakeFiles/paho-mqtt3as-static.dir/SSLSocket.c.o
[ 92%] Built target paho-mqtt3c-static
[ 92%] Built target paho-mqtt3a-static
Scanning dependencies of target MQTTVersion-static
[ 94%] Building C object src/CMakeFiles/MQTTVersion-static.dir/MQTTVersion.c.o
[ 96%] Linking C executable MQTTVersion-static
[ 98%] Linking C static library libpaho-mqtt3cs.a
[ 98%] Built target MQTTVersion-static
[100%] Linking C static library libpaho-mqtt3as.a
[100%] Built target paho-mqtt3cs-static
[100%] Built target paho-mqtt3as-static
Install the project...
-- Install configuration: "Debug"
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/MQTTAsync_publish.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/MQTTAsync_subscribe.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/MQTTClient_publish.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/MQTTClient_publish_async.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/MQTTClient_subscribe.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/paho_c_pub.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/paho_c_sub.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/paho_cs_pub.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/paho_cs_sub.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/samples/pubsub_opts.c
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/CONTRIBUTING.md
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/epl-v20
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/edl-v10
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/README.md
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/share/doc/Eclipse Paho C/notice.html
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/libpaho-mqtt3c.a
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/libpaho-mqtt3a.a
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include/MQTTAsync.h
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include/MQTTClient.h
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include/MQTTClientPersistence.h
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include/MQTTProperties.h
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include/MQTTReasonCodes.h
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include/MQTTSubscribeOpts.h
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include/MQTTExportDeclarations.h
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/libpaho-mqtt3cs.a
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/libpaho-mqtt3as.a
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfig.cmake
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfig-debug.cmake
-- Installing: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfigVersion.cmake
cargo:root=/Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out
debug:CMake output dir: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out
debug:link Using SSL library
debug:Using Paho C library at: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/libpaho-mqtt3as.a
debug:Using Paho C headers at: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/include
debug:Target: x86_64-apple-darwin

--- stderr
fatal: not a git repository (or any of the parent directories): .git
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ASM_COMPILER
    CMAKE_ASM_FLAGS

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpaho-mqtt3cs.a(SHA1.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpaho-mqtt3cs.a(SHA1.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpaho-mqtt3as.a(SHA1.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpaho-mqtt3as.a(SHA1.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/libpaho-mqtt3cs.a(SHA1.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/macbook/Documents/Techwork/rust-test/hello-rust/target/debug/build/paho-mqtt-sys-a130840b46e14d4f/out/lib/libpaho-mqtt3as.a(SHA1.c.o) has no symbols
thread 'main' panicked at 'No generated bindings exist for the version/target: bindings/bindings_paho_mqtt_c_1.3.2-x86_64-apple-darwin.rs', /Users/macbook/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-sys-0.3.0/build.rs:102:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by pikitgb** [comment]
same +1

**Comment by fpagliughi** [comment]
Ugh. Sorry. This was a build "optimization" that obviously didn't go right!

Try to build with the feature `build_bindgen` turned on.

That should fix it. If so, let me know. I should probably make the bindgen build the default in the next version so that this doesn't happen again.

**Comment by fpagliughi** [comment]
An update is in the `develop` branch that should fix the default build.

**Comment by saini-g** [comment]
@fpagliughi  Thanks for the workaround, any idea on when the fix will be included in the main release?

**Comment by fpagliughi** [comment]
Most of the big changes are done. Now there's just a few minor things, then test, test, test. I'm guessing that it will go out in about a week.

But this next version (v0.8) will have a fairly large number of breaking changes, so it may be worth back-porting this build fix to the 0.7 branch as well. I'll test that out in the next day or two.

**Comment by Tockra** [comment]
The default openssl location of macos seems to be wrong.
I always need to set OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ before building.
MACOS: 10.15.5

**Comment by fpagliughi** [comment]
The initial fix went out in v0.8.
In the next, upcoming release (v0.9) there will likely be some new options for linking OpnSSL
