### ISSUE TITLE
Incompatible version with sys on the develop branch

### ISSUE THREAD

**Issue by Sparika** [eclipse/paho.mqtt.rust#76]
Hi,

Thank you for your work. I'm not sure it warrants an issue but the version of the sys crate has been updated to v0.4 in the develop while it still required to be v^0.3  by the main crate.

**Comment by fpagliughi** [comment]
Thanks! Hopefully I would have figured that out when I got back working on the main crate this afternoon, but you never know.

Once the build issues are worked out in the sys crate, this will all get pushed to master and move toward a release. Let me know if you see anything else that looks weird.

**Comment by Sparika** [comment]
I'm just starting to use MQTT with your crate, but sure. If I spot something I will let you know.

**Comment by fpagliughi** [comment]
Great. The develop branch is changing quickly at the moment, but should settle down in a few days.

**Comment by fpagliughi** [comment]
Fixed.
