### ISSUE TITLE
InsecureSkipVerify TLS

### ISSUE THREAD

**Issue by Tockra** [eclipse/paho.mqtt.rust#79]
Hey guys,

in the golang lib is one TLSconfig option which sets this parameter:
```
// InsecureSkipVerify controls whether a client verifies the
    // server's certificate chain and host name.
    // If InsecureSkipVerify is true, TLS accepts any certificate
    // presented by the server and any host name in that certificate.
    // In this mode, TLS is susceptible to man-in-the-middle attacks.
    // This should be used only for testing.
    InsecureSkipVerify bool
```

Is there something equivalent in rust? This is the one setting I didn't copied from my golang script. At the moment I get already a "TCP connect completion failure" message when I want to connect.

T

**Comment by fpagliughi** [comment]
This sounds like the `verify` option in the Rust `SslOptionsBuilder`:
```
    /// Whether to carry out post-connect checks, including that a
    /// certificate matches the given host name.
    pub fn verify(&mut self, on: bool) -> &mut Self { ... }
```
So you can set `verify(false)` if you want.

**Comment by Tockra** [comment]
Okay that isn't right. The equivalent is enable_server_cert_auth
