### ISSUE TITLE
tls://ip  -> unsecure protocol

### ISSUE THREAD

**Issue by Tockra** [eclipse/paho.mqtt.rust#80]
Hi again,

why I get the message when I'm using a tls:// ip ? 
```bash
   Compiling example_mqtt v0.1.0 (/Users/timtannert/example_mqtt)
    Finished dev [unoptimized + debuginfo] target(s) in 0.68s
     Running `target/debug/example_mqtt`
Connecting to host: 'tls://127.0.0.1:8883'
Bad protocol
```

I used this example: https://github.com/eclipse/paho.mqtt.rust/blob/master/examples/ssl_publish.rs

Replaced the given ip address by my `tls://127.0.0.1:8333` and I removed the .pem key_store. Then I added my own .crt file.
After that I got the above output.

T

**Comment by fpagliughi** [comment]
Use:

ssl://

**Comment by Tockra** [comment]
Yes but my broker don't support ssl. It just supports tls. With MQTT.fx I can just connect with TLSv1.x . 
In rust I get `Connecting to host: 'ssl://195.54.35.142:8883'
[-1] TCP/TLS connect failure` when I try to connect via ssl://

**Comment by fpagliughi** [comment]
It uses TLS. Whichever one is installed on the system, unless you specifically set an environment variable during the build to specify the path to a specific version. v1.1 and v1.2 should all work fine. 

It's just that the URI still uses "ssl://" as the prefix. That's all.

Though it makes sense that it could/should also recognize "tls://" for the same thing, to maybe avoid this confusion.

**Comment by Tockra** [comment]
okay. How can I ensure that the crate uses Tlsv1.2 and nothing else?

**Comment by Tockra** [comment]
Skipped with `enable_server_cert_auth(false)`
