### ISSUE TITLE
AsyncClient creates a folder

### ISSUE THREAD

**Issue by Tockra** [eclipse/paho.mqtt.rust#82]
Hi,

is there any reason why
```rust
      // Create the client. Use an ID for a persistent session.
        // A real system should try harder to use a unique ID.
        let create_opts = CreateOptionsBuilder::new()
            .server_uri("ssl://127.0.0.1:8883")
            .client_id("client_id")
            .finalize();

        // Create the client connection
        let cli = AsyncClient::new(create_opts).unwrap_or_else(|e| {
            println!("{} Error creating the client: {:?}", Local::now().format("[%F %T]"), e);
            process::exit(1);
        });
```
creates the folder `client_id-127.0.0.1-8883/` at my project root?
The documentations says nothing about this.

**Comment by fpagliughi** [comment]
That's the default persistence.

**Comment by Tockra** [comment]
> That's the default persistence.

Is there a reason that a client who just subscribe a topic has it? Or is it a publisher thing?

**Comment by fpagliughi** [comment]
The call to create() can't predict what you will do later in the program. If you don't want persisyence, chose `PersistenceType::None` in the create options.
