### ISSUE TITLE
How is version 0.8 coming along?

### ISSUE THREAD

**Issue by svanharmelen** [eclipse/paho.mqtt.rust#89]
Just wondering if the version (even through it has not be released yet) is usable? Or that for now version 0.7.1 is still the only version that can be used safely. And if so, any (super rough) idea when 0.8 will happen? Just curious, of course "no idea" is also a super valid answer!

Thanks!

**Comment by fpagliughi** [comment]
The bad news is that I got really busy for work, which delayed my Paho updates. The good news is that I need Rust v0.8 for work, in a production evvironment... so it will definitely get done "soon".

The version in the "master" branch seems pretty stable so far. I would recommend using that version if you're starting a new project, or if you just want the async/await features. I still need to add some additional updates before a full release, but I don't think there will be any big, breaking changes coming. You should be able to switch from master to the v0.8 release pretty easily when it happens. At this point, I'm expecting the release by mid-September at the latest.

**Comment by fpagliughi** [comment]
And I would *definitely* appreciate any feedback and bug reports on the master version before the release!

**Comment by svanharmelen** [comment]
Sounds good @fpagliughi! I started working on something a while ago (when I opened #67), but also got sidetracked by a shift in priorities. The project now got priority again, so it's planned for the upcoming sprints and I need to pick it up again.

I will do so using `master` for now and will let you know any issues I find. Thanks and I'll keep in touch.
