### ISSUE TITLE
Deadlock calling subscribe from callback

### ISSUE THREAD

**Issue by bittrance** [eclipse/paho.mqtt.rust#96]
I'm trying write a subscriber which has to deal with a broker that does not provide persistent sessions. Putting the subscribe call inside the connected callback seemed a reasonable strategy. However, the below example blocks forever on the subscribe operation.
```
use async_std::task;
use futures::stream::StreamExt;
use paho_mqtt as mqtt;
use std::time::Duration;

#[async_std::test]
async fn reconnecting_subscriber() {
    let mqtt_opts = mqtt::CreateOptionsBuilder::new()
        .server_uri(format!("tcp://localhost:{}", 1883))
        .finalize();
    let mut client = mqtt::AsyncClient::new(mqtt_opts).unwrap();
    let interval = Duration::from_secs(1);
    let conn_opts = mqtt::ConnectOptionsBuilder::new()
        .clean_session(true)
        .automatic_reconnect(interval, interval)
        .finalize();
    client.set_connected_callback(|client| {
        println!("subscribing");
        let res = task::block_on(client.subscribe("too/foo", 0 as i32));
        println!("Result {:?}", res); // We never get here
    });
    client.connect(conn_opts).await.unwrap();
    client
        .get_stream(10)
        .for_each(|message| futures::future::ready(println!("{:?}", message)))
        .await;
}
```
Executing this with a suitable logging setting yields:
```
19700101 010000.000 16 commands restored for client
19700101 010000.000 0 queued messages restored for client
DEBUG - AsyncClient handle: 0x7fe4f8041890
DEBUG - Connecting handle: 0x7fe4f8041890
DEBUG - Connect options: ConnectOptions { copts: MQTTAsync_connectOptions { struct_id: [77, 81, 84, 67], struct_version: 7, keepAliveInterval: 60, cleansession: 1, maxInflight: 65535, will: 0x0, username: 0x0, password: 0x0, connectTimeout: 30, retryInterval: 0, ssl: 0x0, onSuccess: None, onFailure: None, context: 0x0, serverURIcount: 0, serverURIs: 0x0, MQTTVersion: 0, automaticReconnect: 1, minRetryInterval: 1, maxRetryInterval: 1, binarypwd: MQTTAsync_connectOptions__bindgen_ty_1 { len: 0, data: 0x0 }, httpHeaders: 0x0, cleanstart: 0, connectProperties: 0x0, willProperties: 0x0, onSuccess5: None, onFailure5: None }, data: ConnectOptionsData { will: None, ssl: None, user_name: None, password: None, server_uris: StringCollection { c_coll: [], c_mut_coll: [], data: StringCollectionData { coll: [] } }, props: None, will_props: None, http_headers: None } }
19700101 010000.000 Connecting to serverURI localhost:1883 with MQTT version 4
19700101 010000.000 New socket 6 for localhost:1883, port 1883
19700101 010000.000 Connect pending
19700101 010000.000 m->c->connect_state = 1
19700101 010000.000 6  -> CONNECT version 4 clean: 1 (0)
19700101 010000.000 m->c->connect_state = 4
19700101 010000.000 6  <- CONNACK rc: 0
19700101 010000.000 0 responses removed for client
19700101 010000.000 16 commands removed for client
19700101 010000.000 Calling connect success for client
DEBUG - Token success! 0x7fe4f8046850, 0x7fe4f69f6c70
DEBUG - Token completed with code: 0
DEBUG - Expecting server response for: Connect
DEBUG - Got response: ServerResponse { rsp: Connect(ConnectResponse { server_uri: "localhost:1883", mqtt_version: 4, session_present: false }), props: Properties { cprops: MQTTProperties { count: 0, max_count: 0, length: 0, array: 0x0 } }, reason_code: Success }
19700101 010000.000 Calling connected for client
DEBUG - Connected! 0x7fe4f8046540
TRACE - Invoking connected callback
subscribing
DEBUG - Created response for token at: 0x7fe4c80010d0
DEBUG - Subscribe to '"too/foo"' @ QOS 0
TRACE - block_on
```
Replacing subscribe with publish still deadlocks, so it is not specific to subscribe. Somewhat relatedly, it would be a simpler to use callbacks if they could return a future.

This looks like a bug?

**Comment by fpagliughi** [comment]
The problem is that you can't block the callback thread. That's the processing thread from the underlying C library, and any blocking call will cause the library to deadlock.

Try just removing the wait, like:
```
    client.set_connected_callback(|client| {
        println!("subscribing");
        client.subscribe("too/foo", 0 as i32);
    });
```

It's a little weird, because essentially the threads in the C lib are acting like an async executor for us, and we're using the library callbacks to move the futures forward. 

So the notion that futures "don't do anything until passed into an executor" is not exactly true here. The calls like _subscribe()_ pass the request to the C lib which starts executing them immediately, and returns a future that will eventually be marked completed by a C callback. 

Funnily this is not how futures are documented, but it's how several of their tutorials showing how to implement a Future are done.

**Comment by fpagliughi** [comment]
The bigger problem with the library is that we keep adding API's without removing old ones and it gets confusing in that you can mix and match different techniques, although they don't always work well together.

Since you're using async/await, it would probably be better to stick with that for the whole solution. So just await the connect, subscribe, then start pulling messages from the stream:

```
    let conn_opts = mqtt::ConnectOptionsBuilder::new()
        .clean_session(true)
        .automatic_reconnect(interval, interval)
        .finalize();
    client.connect(conn_opts).await.unwrap();
    client.subscribe("too/foo", 0).await.unwrap();
    client
        .get_stream(10)
        .for_each(|message| futures::future::ready(println!("{:?}", message)))
        .await;
```

**Comment by tobdub** [comment]
One option may be to hide different APIs behind features, e.g. `sync` and `async`. This could also help to reduce compile times and code size.

**Comment by bittrance** [comment]
I see I was unclear in my original post. What I meant to say was that I am trying to explicitly resubscribe when `automatic_reconnect` has reestablished a broken connection. As far as I can tell, the connected callback is the best trigger for detecting that a connection was (re)established. 

I care about the success of the subscribe call, so I can't just make it a throw-away call.

> The calls like subscribe() pass the request to the C lib which starts executing them immediately

It is early days, so I don't presume to know what will be common, but I suspect this risks giving rise to subtle timing bugs. Rust futures encourages "mixed" style futures programming (a combination of "synchronous-looking" (i.e. .await) code and composable (i.e. .then(...).then(...)) code) which makes it tricky to see exactly when a piece of code is actually executed.

When working with futures, I think I would have preferred an event stream over callbacks in the async client. Something like
```
let events = client.events(vec![AsyncEventType::Connected]).get_stream();
while let Some(event) = events.next().await { match  event { ... } }    .
```
would have been easy to work with. (Splitting the current AsyncClient into one that is callback-oriented and one that is futures-oriented might make sense.)

In the case at hand, I suppose I will have to create a separate event queue and push an event onto it from the callback. As far as I'm concerned, this issue can be closed. Thank you for the response.
