### ISSUE TITLE
Example on passing the client to a thread

### ISSUE THREAD

**Issue by mlmarius** [eclipse/paho.mqtt.rust#97]
Hi! My program needs to perform some operations in the background. These operations need to somehow wait for a while and then signal that the operation has completed. Currently, my program, without being integrated to work with paho-mqtt spawns a thread that loops receiving data via a channel, performs the required task, sleeps for some amount of time. Problem is that at the end of which loop I may need to use the paho client to dispatch a message. Given that the paho client was created in the main thread, what options are there to be able to use it from the subthread while still consuming in the main thread?

**Comment by fpagliughi** [comment]
The `AsyncClient` is thread safe. The implementation of it is just an Arc to an inner client struct, so it is cheap and easy to clone.
https://github.com/eclipse/paho.mqtt.rust/blob/976e7ea538d75b960731183515207ee40dd6a153/src/async_client.rs#L93-L96

So just create a clone of the client and send it to the second thread. That's probably the easiest thing to do.
