### ISSUE TITLE
Update support for Paho C to v1.3.8

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.rust#99]
There have been several releases to the underlying Paho C library over the last few months. The next Rust release should target the latest one, Paho C v1.3.6

**Comment by fpagliughi** [comment]
This will fix a few bugs that were in the C lib, such as:
https://github.com/eclipse/paho.mqtt.c/issues/972

**Comment by fpagliughi** [comment]
The target was bumped to v1.3.7 as it added some additional fixes and also support for websocket HTTP/S proxies.

Unfortunately, a fix that went into v1.3.5 has broken our user-defined persistence, which is very important to me personally, but either way, I wouldn't want to put out a release with a known bug like that. I submitted a possible fix to the C lib, and hopefully the matter will be resolved soon.

https://github.com/eclipse/paho.mqtt.c/issues/1001

**Comment by fpagliughi** [comment]
There was an incompatibility in v1.3.7 with our user-defined persistence, so we needed to wait for a fix in 1.3.8.

**Comment by svanharmelen** [comment]
Super nice that v0.9 is out! I'll be trying out the new websocket support first thing next year 😃

**Comment by fpagliughi** [comment]
Awesome. Any feedback will be helpful. I needed to get the new version out because the bugs in the C lib were holding people up, but I didn't finish all the new features that I wanted to get in, particularly the ideas from #101.

I'm going to keep working to get a few more things in and put out a v0.9.1 release in a few weeks.
